local A, L = ...
local addonpath = "Interface\\AddOns\\"..A.."\\"

-- Register new textures with LibSharedMedia
LSM = LibStub("LibSharedMedia-3.0")
LSM:Register(LSM.MediaType.STATUSBAR, "MystlerBar01", addonpath.."tex\\MystlerBar01")
LSM:Register(LSM.MediaType.STATUSBAR, "MystlerBar02", addonpath.."tex\\MystlerBar02")
LSM:Register(LSM.MediaType.STATUSBAR, "MystlerBar03", addonpath.."tex\\MystlerBar03")
LSM:Register(LSM.MediaType.STATUSBAR, "MystlerBar04", addonpath.."tex\\MystlerBar04")

-- Register fonts
LSM:Register(LSM.MediaType.FONT, "Roboto-Bold", addonpath.."fonts\\Roboto-Bold.ttf")
LSM:Register(LSM.MediaType.FONT, "Roboto-Regular", addonpath.."fonts\\Roboto-Regular.ttf")

-- Register some of our sounds
LSM:Register(LSM.MediaType.SOUND, "Assassinen", addonpath.."sfx\\assassinen.ogg")
LSM:Register(LSM.MediaType.SOUND, "DunDunDaah", addonpath.."sfx\\defeat.ogg")
LSM:Register(LSM.MediaType.SOUND, "BloodlustTime", addonpath.."sfx\\bloodlust.ogg")
LSM:Register(LSM.MediaType.SOUND, "PoisonAlert", addonpath.."sfx\\poison.ogg")
LSM:Register(LSM.MediaType.SOUND, "BuffAlert", addonpath.."sfx\\buff.ogg")

LSM:Register(LSM.MediaType.SOUND, "DeathComes", addonpath.."sfx\\ow\\deathcomes.ogg")
LSM:Register(LSM.MediaType.SOUND, "DeathFromAbove", addonpath.."sfx\\ow\\deathfromabove.ogg")
LSM:Register(LSM.MediaType.SOUND, "DidThatSting", addonpath.."sfx\\ow\\didthatsting.ogg")
LSM:Register(LSM.MediaType.SOUND, "DieDieDie", addonpath.."sfx\\ow\\die.ogg")
LSM:Register(LSM.MediaType.SOUND, "HeroesNeverDie", addonpath.."sfx\\ow\\heroesneverdie.ogg")
LSM:Register(LSM.MediaType.SOUND, "DropTheBeat", addonpath.."sfx\\ow\\letsdropthebeat.ogg")
LSM:Register(LSM.MediaType.SOUND, "WatchingOverYou", addonpath.."sfx\\ow\\watchingoveryou.ogg")
LSM:Register(LSM.MediaType.SOUND, "InMySights", addonpath.."sfx\\ow\\ivegotyou.ogg")
LSM:Register(LSM.MediaType.SOUND, "YourAttention", addonpath.."sfx\\ow\\doihaveyourattention.ogg")
LSM:Register(LSM.MediaType.SOUND, "BarrierUp", addonpath.."sfx\\ow\\barrierup.ogg")
LSM:Register(LSM.MediaType.SOUND, "HighNoon", addonpath.."sfx\\ow\\highnoon.ogg")
LSM:Register(LSM.MediaType.SOUND, "SpeedBoost", addonpath.."sfx\\ow\\speedboost.ogg")
LSM:Register(LSM.MediaType.SOUND, "ExperienceTranquility", addonpath.."sfx\\ow\\tranquility.ogg")
LSM:Register(LSM.MediaType.SOUND, "GetBack", addonpath.."sfx\\ow\\getback.ogg")
LSM:Register(LSM.MediaType.SOUND, "GetBehindMe", addonpath.."sfx\\ow\\getbehindme.ogg")
LSM:Register(LSM.MediaType.SOUND, "Repositioning", addonpath.."sfx\\ow\\repos.ogg")
LSM:Register(LSM.MediaType.SOUND, "TracerBlink", addonpath.."sfx\\ow\\blink.ogg")
LSM:Register(LSM.MediaType.SOUND, "ReinhardtCharge", addonpath.."sfx\\ow\\charge.ogg")
LSM:Register(LSM.MediaType.SOUND, "AnchorsAway", addonpath.."sfx\\ow\\anchors.ogg")
LSM:Register(LSM.MediaType.SOUND, "DontBeShy", addonpath.."sfx\\ow\\dontbeshy.ogg")
LSM:Register(LSM.MediaType.SOUND, "JusticeRains", addonpath.."sfx\\ow\\justice.ogg")
LSM:Register(LSM.MediaType.SOUND, "HoldUpNow", addonpath.."sfx\\ow\\holdupnow.ogg")
LSM:Register(LSM.MediaType.SOUND, "MoooltenCooore", addonpath.."sfx\\ow\\moltencore.ogg")
LSM:Register(LSM.MediaType.SOUND, "OhMyGosh", addonpath.."sfx\\ow\\omg.ogg")
LSM:Register(LSM.MediaType.SOUND, "MeiUltimate", addonpath.."sfx\\ow\\meiult.ogg")
LSM:Register(LSM.MediaType.SOUND, "JunkratGotcha", addonpath.."sfx\\ow\\gotcha.ogg")
LSM:Register(LSM.MediaType.SOUND, "BackInTheSaddleAgain", addonpath.."sfx\\ow\\backinthesaddle.ogg")
LSM:Register(LSM.MediaType.SOUND, "JunkratFireInTheHole", addonpath.."sfx\\ow\\fireinthehole.ogg")
LSM:Register(LSM.MediaType.SOUND, "ISeeYou", addonpath.."sfx\\ow\\iseeyou.ogg")
LSM:Register(LSM.MediaType.SOUND, "IllRaceYa", addonpath.."sfx\\ow\\illraceya.ogg")
LSM:Register(LSM.MediaType.SOUND, "ReaperWraithWalk", addonpath.."sfx\\ow\\wraithwalk.ogg")
LSM:Register(LSM.MediaType.SOUND, "OneManApocalypse", addonpath.."sfx\\ow\\onemanapocalypse.ogg")
LSM:Register(LSM.MediaType.SOUND, "JunkratLaugh", addonpath.."sfx\\ow\\junkratlaugh.ogg")
LSM:Register(LSM.MediaType.SOUND, "SquealForMe", addonpath.."sfx\\ow\\squealforme.ogg")
LSM:Register(LSM.MediaType.SOUND, "RoadhogShutUp", addonpath.."sfx\\ow\\shutup.ogg")
LSM:Register(LSM.MediaType.SOUND, "WereAllAnimals", addonpath.."sfx\\ow\\wereallanimals.ogg")
LSM:Register(LSM.MediaType.SOUND, "JusticeWillBeDone", addonpath.."sfx\\ow\\justicewillbedone.ogg")
LSM:Register(LSM.MediaType.SOUND, "BeShielded", addonpath.."sfx\\ow\\beshielded.ogg")
LSM:Register(LSM.MediaType.SOUND, "DarknessConsumes", addonpath.."sfx\\ow\\thedarkness.ogg")
LSM:Register(LSM.MediaType.SOUND, "AngelOfDeath", addonpath.."sfx\\ow\\angelofdeath.ogg")
